version: '3.8'
services:
  medley-minio:
    container_name: medley-minio
    image: minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - medley_core-network
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"

networks:
  medley_core-network:
    external: true

volumes:
    minio_data:
