name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
