name: Deploy Auth App

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      - '.github/workflows/deploy-auth.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./auth
          file: ./auth/Dockerfile
          push: true
          tags: mariuscourquin62/medley-auth:latest